[build]
  base = "/"

  publish = "build/"

  command = "npm run build"

[context.production]
  environment = { NODE_VERSION = "18.20.4" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  targetPort = 3000
  port = 8888
  